logging:
  path: /var/yuuyoo
  config: classpath:logback-production.xml

---
spring:
  profiles: pro-eureka
eureka:
  instance:
    #instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
    instanceId: ${spring.cloud.client.ipAddress}:${spring.application.name}:${server.port}:@project.version@
  client:
    serviceUrl:
      defaultZone: http://yuuyoo-eureka:8761/eureka

---
spring:
  profiles: pro-redis
  redis:
    host: yuuyoo-redis
    port: 6379