spring:
  profiles.active: dev
  jackson.serialization.WRITE_DATES_AS_TIMESTAMPS: true

management:
  endpoints:
    web:
      base-path: /manage
      path-mapping.health: status
  endpoint:
    health:
      #show-details: always
      enabled: true

---
spring:
  profiles: dev-eureka
eureka:
  #instance:
    #instanceId: ${spring.cloud.client.ipAddress}:${spring.application.name}:${server.port}:@project.version@
  client:
    serviceUrl:
      #defaultZone: http://localhost:8761/eureka
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}


---
spring:
  profiles: dev-redis
  redis:
    host: localhost
    port: 6379