logging:
  path: /var/yuuyoo
  config: classpath:logback-production.xml

---
spring:
  profiles: svt-eureka
eureka:
  instance:
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
  client:
    serviceUrl:
      defaultZone: http://yuuyoo-eureka:8761/eureka

---
spring:
  profiles: svt-redis
  redis:
    host: yuuyoo-redis
    port: 6379
