server.port: 8761
management:
  server:
    port: 8762

#Slogging:
#  file: eureka.log

eureka:
  instance:
    homePageUrl: http://${eureka.instance.hostname}/
  server:
    enableSelfPreservation: false

spring:
  profiles.include: standalone
---
spring:
  profiles: standalone
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/